	if(i->left!=NULL&&i->right!=NULL)
	{
		if(i->right->h>i->left->h)
			i->h=i->left->h+1;
		else 
			i->h=i->right->h+1;
		i->nodes=((i->left->nodes%m*i->right->nodes%m)%m*P)%m;
		if(i->right->val!=i->val)
			i->hash=(i->left->hash+((i->val+i->right->hash)%m*(i->left->nodes*P)%m)%m)%m;
		else
		{
			if(i->right->left!=NULL)
				i->hash=i->left->hash+((i->right->hash*i->left->nodes)%m*P)%m+(((i->val*i->right->left->nodes)%m*(P*P)%m)%m*i->left->nodes)%m;
			else
				i->hash=(i->left->hash+((i->right->hash*i->left->nodes)%m*P)%m+(((i->val*P)%m*P)%m*i->left->nodes)%m)%m;
		}
	}
	else if(i->right!=NULL)
	{
		i->h=i->right->h+1;
		i->nodes=(i->right->nodes*P)%m;
		if(i->val!=i->right->val)
			i->hash=((i->val+i->right->hash)%m*P)%m;
		else
		{
			if(i->right->left!=NULL)
				i->hash=((((i->val*i->right->left->nodes)%m*P)%m*P)%m+(i->right->hash*P)%m)%m;
			else
				i->hash=(((i->val*P)%m*P)%m+(i->right->hash*P)%m)%m;
		}
	}
	else if(i->left!=NULL)
	{
		i->h=i->left->h+1;
		i->nodes=(i->left->nodes*P)%m;
		i->hash=(i->left->hash+(i->val*i->nodes)%m)%m;
	}
	else
	{
		i->h=1;
		i->nodes=P;
		i->hash=(i->val*P)%m;
	}
